import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Navigation from "../components/Navigation";
import SessionWrapper from "../components/SessionWrapper";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <SessionWrapper>
                <Navbar />
                {/* <Navigation className="" /> */}
                <div className="text-center  mb-14">{children}</div>
                <Footer />
            </SessionWrapper>
        </>
    );
}
