import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Navigation from "../components/Navigation";
import SessionWrapper from "../components/SessionWrapper";

export const metadata = {
    title: "Service Station",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <SessionWrapper>
                <Navbar />
                <div className="text-center py-20 h-full">{children}</div>
                <Footer />
            </SessionWrapper>
        </>
    );
}
